stages:
  - deploy_dev

deploy-to-dev-server:
  stage: deploy_dev
  rules:
    - if: $CI_COMMIT_BRANCH == 'master'
  script:
    - rsync -av --no-perms --no-owner --no-group --filter=':- .gitignore' --delete-after $CI_PROJECT_DIR/ /var/www/git/pmi_dashboard_front
    - echo "Application successfully deployed on dev server"
    - docker compose -f /var/www/git/pmi_dashboard_front/docker-compose.yml up -d --build
    - echo "Application run..."
  tags:
    - monitoring_pmi
