services:
  pmi_front:
    container_name: pmi_front
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:3123:3000"
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "5M"
        max-file: 10
    networks:
      - pmi_network

networks:
  pmi_network:
    external: true
