/** @type {import('tailwindcss').Config} */

module.exports = {
  darkMode: ['class', '[data-mantine-color-scheme="dark"]'],
  purge: {
    enabled: true,
    options: {
      safelist: ['light', 'dark'], //specific classes
    },
  },
  content: ['./src/**/*.{js,ts,jsx,tsx,mdx}'],
  theme: {
    extend: {
      backgroundImage: {
        'blue-gradient': 'linear-gradient(99deg, #32419B -13.21%, rgba(50, 65, 155, 0.00) 94.15%)',
        'gradient-radial': 'radial-gradient(var(--tw-gradient-stops))',
        'gradient-conic': 'conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))',
        'layout-bg': 'linear-gradient(109deg, #131B4B 13%, #2B3674 52.1%)',
      },
      colors: {
        main_alice_blue: '#F2F3F9',
        main_black: '#000000',
        'main-blue': '#414FA1',
        main_blue_1: '#4C5AAD',
        main_blue_2: '#6271C5',
        main_blue_3: '#404E9A',
        main_blue_4: '#253071',
        main_blue_5: 'rgba(64, 78, 154, 0.80)',
        main_blue_6: '#99A0C5',
        main_blue_7: '#39468E',
        main_blue_8: '#4E5DB1',
        main_bright_sky_blue: '#18D5FF',
        main_cool_gray: '#7A86A8',
        main_dark_blue: '#131B4B',
        main_dark_slate_blue: '#5A5881',
        main_deep_blue: '#2B3674',
        main_deep_gray: '#F5F5F9',
        main_electric_indigo: '#4318FF',
        main_fire_engine_red: '#E93A3A',
        main_gainsboro: '#EAECEC',
        main_ghost_white: '#F7FAFF',
        main_ghostGray: '#9CA0B2',
        main_green_pigment: '#01A54A',
        main_lavender_mist: '#F3F2FA',
        main_lavender_mist_alt: '#F4F7FE',
        main_light_aquamarine: '#05CD991A',
        main_light_black: '#0000000A',
        main_light_blue: '#DDE3F6',
        main_light_cornflower_blue: '#C8D8FF',
        main_light_gray: '#E5EAF1',
        main_light_green: '#F5FCFF',
        main_light_slate_blue: '#A3AED0',
        main_light_steel_blue: '#D3E2E9',
        main_light_white: '#FFFFFFCF',
        main_medium_aquamarine: '#05CD99',
        main_medium_blue: '#0183C6',
        main_medium_spring_green: '#1CEAB4',
        main_pale_cyan: '#E6F3FA',
        main_periwinkle: '#D3E0FF',
        main_purple_x11: '#5934FD',
        main_slate: '#707EAE',
        main_thin_white: '#EBEAF3',
        main_vivid_sky_blue: '#42BCFB',
        main_white: '#FFFFFF',
        main_white_smoke: '#FBFCFD',
        main_transparent_white: '#111111',
        content_box_bg: 'rgba(250, 252, 255, 0.81)',
      },
      screens: {
        sm: '640px',
        md: '768px',
        lg: '1024px',
        xl: '1280px',
        '2xl': '1536px',
        '3xl': '1920px',
      },
      letterSpacing: {
        tightest: '-0.28px',
      },
    },
  },
  plugins: [],
};
