import {
  IconAdjustmentsCog,
  IconBinaryTree,
  IconBorderAll,
  IconBrandStackshare,
  IconBriefcase,
  IconCategory,
  IconHome,
  IconLanguage,
  IconMap2,
  IconMapPin,
  IconPaint,
  IconSettings,
  IconUser,
} from '@tabler/icons-react';

import { Branch, Door } from '@/assets/icons';

export const sidebarList = () => {
  return [
    {
      id: 'general_statistics',
      title: 'Umumiy statistika',
      icon: IconHome,
      type: 'page',
      path: '/',
    },
    {
      id: 'project_list',
      title: 'Loyihalar',
      icon: Branch,
      type: 'page',
      path: '/project-list',
    },
    {
      id: 'section_of_branches',
      title: 'Sohalar',
      icon: Branch,
      type: 'page',
      path: '/section-of-branches',
    },
    // {
    //   id: 'section_of_regions',
    //   title: 'Hududlar kesimida',
    //   icon: IconMapPin,
    //   type: 'page',
    //   path: '/section-of-regions',
    //   role: ['super_admin', 'admin'],
    // },
    // {
    //   id: 'classification',
    //   title: 'Sohalar kesimida',
    //   icon: IconBriefcase,
    //   type: 'page',
    //   path: '/classification',
    //   role: ['super_admin', 'admin'],
    // },
    // {
    //   id: 'organizations_section',
    //   title: 'Tashkilotlar kesimida',
    //   icon: Door,
    //   type: 'page',
    //   path: '/section-of-organizations',
    //   role: ['super_admin', 'admin'],
    // },
    // {
    //   id: 'sources',
    //   title: 'Manbalar kesimida',
    //   icon: IconBrandStackshare,
    //   type: 'page',
    //   path: '/sources',
    //   role: ['super_admin', 'admin'],
    // },
    {
      id: 'settings',
      title: 'Settings',
      icon: IconSettings,
      type: 'dropdown',
      path: '/settings',
      role: ['super_admin'],
      children: [
        {
          id: 'country-list',
          title: 'Countries',
          icon: IconBinaryTree,
          type: 'page',
          path: '/settings/country-list',
        },
        // {
        //   id: 'executor',
        //   title: 'Executor',
        //   icon: IconUser,
        //   type: 'page',
        //   path: '/settings/executor',
        // },
        // {
        //   id: 'scales-table',
        //   title: 'Scales table',
        //   icon: IconBorderAll,
        //   type: 'page',
        //   path: '/settings/scales-table',
        // },
        // {
        //   id: 'scales-settings',
        //   title: 'Scales settings',
        //   icon: IconAdjustmentsCog,
        //   type: 'page',
        //   path: '/settings/scales-settings',
        // },
        {
          id: 'scales-color-settings',
          title: 'Scale color settings',
          icon: IconAdjustmentsCog,
          type: 'page',
          path: '/settings/scales-color-settings',
        },
        {
          id: 'colors-list',
          title: 'Colors list',
          icon: IconPaint,
          type: 'page',
          path: '/settings/colors-list',
        },
        {
          id: 'colors-field-list',
          title: 'Color fields',
          icon: IconPaint,
          type: 'page',
          path: '/settings/colors-field-list',
        },
        {
          id: 'assign-colors-list',
          title: 'Assign colors',
          icon: IconPaint,
          type: 'page',
          path: '/settings/assign-colors-list',
        },
        {
          id: 'soato-region',
          title: 'Soato region',
          icon: IconMap2,
          type: 'page',
          path: '/settings/soato-region',
        },
        {
          id: 'source-list',
          title: 'Source list',
          icon: IconBrandStackshare,
          type: 'page',
          path: '/settings/source-list',
        },
        // {
        //   id: 'translation',
        //   title: 'Translation',
        //   icon: IconLanguage,
        //   type: 'page',
        //   path: '/settings/translation',
        // },
      ],
    },
  ];
};
